export const MONGOLOQUENT_MODULE = "MONGOLOQUENT_MODULE";
export const MONGOLOQUENT_DB = "MONGOLOQUENT_DB";
export const MONGOLOQUENT_TRANSACTIONAL = "MONGOLOQUENT_TRANSACTIONAL";
export const MONGOLOQUENT_TRANSACTIONAL_NAME = "MONGOLOQUENT_TRANSACTIONAL_NAME";
export const MONGOLOQUENT_TRANSACTIONAL_RETRIES = "MONGOLOQUENT_TRANSACTIONAL_RETRIES";
